### ISSUE TITLE
七牛上传有概率丢失（少上传）文件

### ISSUE THREAD

**Issue by 2015WUJI01** [cnbattle/upcloud#1]
七牛好像限制了并发上传，不能同时上传太多文件，配置文件里并发数量高的时候丢失率也高。  
并发数量改成 1 的时候还是会有丢失的情况。
上传的时候 sleep 半秒试试？最近比较忙，暂时没时间提 PR 了，等我有时间仔细研究一下。

**Comment by cnbattle** [comment]
我先测试看下，只是用过没发现

**Comment by cnbattle** [comment]
我尝试修复了这个问题  https://github.com/cnbattle/upcloud/commit/575f98911bf6b621dc892b5b3e50fd84f83da584

有时间的话，使用最新的代码试试
